<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
		
     <?php 

        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'));
  
        echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ; 
        echo $this->headScript();

        $this->inlineScript()->captureStart();
        echo <<<JS
	    		if('ontouchstart' in document.documentElement) document.write("<script src='../ace/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
JS;
        $this->inlineScript()->captureEnd();
        
        ?>

    </head>
    <body class="no-skin">
          <div class="navbar navbar-default    navbar-collapse       h-navbar" id="navbar">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div id="navbar-container" class="navbar-container">
				<div class="navbar-header pull-left">
					<!-- #section:basics/navbar.layout.brand -->
					<a class="navbar-brand" href="#">
						<small>
							<i class="fa fa-leaf"></i>
							Ace Admin
						</small>
					</a>

					<!-- /section:basics/navbar.layout.brand -->

					<!-- #section:basics/navbar.toggle -->
					<button data-target=".navbar-buttons,.navbar-menu" data-toggle="collapse" type="button" class="pull-right navbar-toggle navbar-toggle-img collapsed">
						<span class="sr-only">Toggle user menu</span>

						<img alt="Jason's Photo" src="../ace/assets/avatars/user.jpg">
					</button>

					<button data-target=".sidebar" data-toggle="collapse" type="button" class="pull-right navbar-toggle collapsed">
						<span class="sr-only">Toggle sidebar</span>

						<span class="icon-bar"></span>

						<span class="icon-bar"></span>

						<span class="icon-bar"></span>
					</button>

					<!-- /section:basics/navbar.toggle -->
				</div>

				<!-- #section:basics/navbar.dropdown -->
				<div role="navigation" class="navbar-buttons navbar-header pull-right  collapse navbar-collapse">
					<ul class="nav ace-nav">
						<li class="transparent">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								<i class="ace-icon fa fa-bell icon-animated-bell"></i>
							</a>

							<div class="dropdown-menu-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
								<div class="tabbable">
									<ul class="nav nav-tabs">
										<li class="active">
											<a href="#navbar-tasks" data-toggle="tab">
												Tasks
												<span class="badge badge-danger">4</span>
											</a>
										</li>

										<li>
											<a href="#navbar-messages" data-toggle="tab">
												Messages
												<span class="badge badge-danger">5</span>
											</a>
										</li>
									</ul><!-- .nav-tabs -->

									<div class="tab-content">
										<div class="tab-pane in active" id="navbar-tasks">
											<ul class="dropdown-menu-right dropdown-navbar dropdown-menu">
												<li>
													<a href="#">
														<div class="clearfix">
															<span class="pull-left">Software Update</span>
															<span class="pull-right">65%</span>
														</div>

														<div class="progress progress-mini">
															<div class="progress-bar" style="width:65%"></div>
														</div>
													</a>
												</li>

												<li>
													<a href="#">
														<div class="clearfix">
															<span class="pull-left">Hardware Upgrade</span>
															<span class="pull-right">35%</span>
														</div>

														<div class="progress progress-mini">
															<div class="progress-bar progress-bar-danger" style="width:35%"></div>
														</div>
													</a>
												</li>

												<li>
													<a href="#">
														<div class="clearfix">
															<span class="pull-left">Unit Testing</span>
															<span class="pull-right">15%</span>
														</div>

														<div class="progress progress-mini">
															<div class="progress-bar progress-bar-warning" style="width:15%"></div>
														</div>
													</a>
												</li>

												<li>
													<a href="#">
														<div class="clearfix">
															<span class="pull-left">Bug Fixes</span>
															<span class="pull-right">90%</span>
														</div>

														<div class="progress progress-mini progress-striped active">
															<div class="progress-bar progress-bar-success" style="width:90%"></div>
														</div>
													</a>
												</li>

												<li class="dropdown-footer">
													<a href="#">
														See tasks with details
														<i class="ace-icon fa fa-arrow-right"></i>
													</a>
												</li>
											</ul>
										</div><!-- /.tab-pane -->

										<div class="tab-pane" id="navbar-messages">
											<ul class="dropdown-menu-right dropdown-navbar dropdown-menu">
												<li class="dropdown-content ace-scroll" style="position: relative;"><div class="scroll-track" style="display: none;"><div class="scroll-bar"></div></div><div class="scroll-content" style="max-height: 200px;">
													<ul class="dropdown-menu dropdown-navbar">
														<li>
															<a href="#">
																<img alt="Alex's Avatar" class="msg-photo" src="../ace/assets/avatars/avatar.png">
																<span class="msg-body">
																	<span class="msg-title">
																		<span class="blue">Alex:</span>
																		Ciao sociis natoque penatibus et auctor ...
																	</span>

																	<span class="msg-time">
																		<i class="ace-icon fa fa-clock-o"></i>
																		<span>a moment ago</span>
																	</span>
																</span>
															</a>
														</li>

														<li>
															<a href="#">
																<img alt="Susan's Avatar" class="msg-photo" src="../ace/assets/avatars/avatar3.png">
																<span class="msg-body">
																	<span class="msg-title">
																		<span class="blue">Susan:</span>
																		Vestibulum id ligula porta felis euismod ...
																	</span>

																	<span class="msg-time">
																		<i class="ace-icon fa fa-clock-o"></i>
																		<span>20 minutes ago</span>
																	</span>
																</span>
															</a>
														</li>

														<li>
															<a href="#">
																<img alt="Bob's Avatar" class="msg-photo" src="../ace/assets/avatars/avatar4.png">
																<span class="msg-body">
																	<span class="msg-title">
																		<span class="blue">Bob:</span>
																		Nullam quis risus eget urna mollis ornare ...
																	</span>

																	<span class="msg-time">
																		<i class="ace-icon fa fa-clock-o"></i>
																		<span>3:15 pm</span>
																	</span>
																</span>
															</a>
														</li>

														<li>
															<a href="#">
																<img alt="Kate's Avatar" class="msg-photo" src="../ace/assets/avatars/avatar2.png">
																<span class="msg-body">
																	<span class="msg-title">
																		<span class="blue">Kate:</span>
																		Ciao sociis natoque eget urna mollis ornare ...
																	</span>

																	<span class="msg-time">
																		<i class="ace-icon fa fa-clock-o"></i>
																		<span>1:33 pm</span>
																	</span>
																</span>
															</a>
														</li>

														<li>
															<a href="#">
																<img alt="Fred's Avatar" class="msg-photo" src="../ace/assets/avatars/avatar5.png">
																<span class="msg-body">
																	<span class="msg-title">
																		<span class="blue">Fred:</span>
																		Vestibulum id penatibus et auctor  ...
																	</span>

																	<span class="msg-time">
																		<i class="ace-icon fa fa-clock-o"></i>
																		<span>10:09 am</span>
																	</span>
																</span>
															</a>
														</li>
													</ul>
												</div></li>

												<li class="dropdown-footer">
													<a href="inbox.html">
														See all messages
														<i class="ace-icon fa fa-arrow-right"></i>
													</a>
												</li>
											</ul>
										</div><!-- /.tab-pane -->
									</div><!-- /.tab-content -->
								</div><!-- /.tabbable -->
							</div><!-- /.dropdown-menu -->
						</li> 

						<!-- /section:basics/navbar.user_menu -->
					</ul>
				</div>

				<!-- /section:basics/navbar.dropdown -->
				<nav class="navbar-menu pull-left collapse navbar-collapse" role="navigation">
					  
					<!-- /section:basics/navbar.nav -->

					<!-- #section:basics/navbar.form -->
					<form role="search" class="navbar-form navbar-left form-search">
						<div class="form-group">
							<input type="text" placeholder="search">
						</div>

						<button class="btn btn-xs btn-info2" type="button">
							<i class="ace-icon fa fa-search icon-only bigger-110"></i>
						</button>
					</form>

					<!-- /section:basics/navbar.form -->
				</nav>
			</div><!-- /.navbar-container -->
		</div>
       
       
       
        <div id="main-container" class="main-container">
             <?php echo $this->content;
             ?>
            <hr>
            
            <div class="footer">
				<div class="footer-inner">
					<!-- #section:basics/footer -->
					<div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Ace</span>
							Application &copy; 2013-2014
						</span>

						&nbsp; &nbsp;
						<span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
					</div>

					<!-- /section:basics/footer -->
				</div>
			</div>
        </div> <!-- /container -->
        <?php 
        
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
       
        ->prependStylesheet($this->basePath() . '/ace/assets/css/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/ace/assets/css/font-awesome.min.css')
        ->prependStylesheet($this->basePath() . '/ace/assets/css/ace-fonts.css')
        ->prependStylesheet($this->basePath() . '/ace/assets/css/ace.min.css','screen',
        		true,array('id' => 'main-ace-style' ))
        		->prependStylesheet($this->basePath() . '/ace/assets/css/ace-part2.min.css','screen','if lte IE 9')
        		->prependStylesheet($this->basePath() . '/ace/assets/css/ace-skins.min.css')
        		->prependStylesheet($this->basePath() . '/ace/assets/css/ace-rtl.min.css')
        		->prependStylesheet($this->basePath() . '/ace/assets/css/ace-ie.min.css','screen','if lte IE 9')
        		->prependStylesheet($this->basePath() . '/ace/assets/js/ace-extra.min.js')
        		->prependStylesheet($this->basePath() . '/ace/assets/js/html5shiv.min.js','screen','if lte IE 8')
        		->prependStylesheet($this->basePath() . '/ace/assets/js/respond.min.js','screen','if lte IE 8');	
         
        $this->inlineScript()
	        ->prependFile($this->basePath() . '/ace/assets/js/flot/jquery.flot.resize.min.js')
	        ->prependFile($this->basePath() . '/ace/assets/js/flot/jquery.flot.pie.min.js')
	        ->prependFile($this->basePath() . '/ace/assets/js/flot/jquery.flot.min.js')
	        ->prependFile($this->basePath() . '/ace/assets/js/jquery.sparkline.min.js')
	        ->prependFile($this->basePath() . '/ace/assets/js/jquery.easypiechart.min.js')
	        ->prependFile($this->basePath() . '/ace/assets/js/jquery.ui.touch-punch.min.js')
	        ->prependFile($this->basePath() . '/ace/assets/js/jquery-ui.custom.min.js');        
        echo $this->inlineScript()
        ?>
    </body>
</html>
