<div >
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<!-- #section:basics/sidebar -->
			<div class="sidebar                  responsive" id="sidebar">
				<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
				</script>

				<div id="sidebar-shortcuts" class="sidebar-shortcuts">
					<div id="sidebar-shortcuts-large" class="sidebar-shortcuts-large">
						<button class="btn btn-success">
							<i class="ace-icon fa fa-signal"></i>
						</button>

						<button class="btn btn-info">
							<i class="ace-icon fa fa-pencil"></i>
						</button>

						<!-- #section:basics/sidebar.layout.shortcuts -->
						<button class="btn btn-warning">
							<i class="ace-icon fa fa-users"></i>
						</button>

						<button class="btn btn-danger">
							<i class="ace-icon fa fa-cogs"></i>
						</button>

						<!-- /section:basics/sidebar.layout.shortcuts -->
					</div>

					<div id="sidebar-shortcuts-mini" class="sidebar-shortcuts-mini">
						<span class="btn btn-success"></span>

						<span class="btn btn-info"></span>

						<span class="btn btn-warning"></span>

						<span class="btn btn-danger"></span>
					</div>
				</div><!-- /.sidebar-shortcuts -->

				<ul class="nav nav-list" style="top: 0px;">
					<li class="">
						<a href="index.html">
							<i class="menu-icon fa fa-tachometer"></i>
							<span class="menu-text"> Dashboard </span>
						</a>

						<b class="arrow"></b>
					</li>

					<li class="active open hsub">
						<a class="dropdown-toggle" href="#">
							<i class="menu-icon fa fa-desktop"></i>
							<span class="menu-text"> UI &amp; Elements </span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<li class="hsub">
								<a class="dropdown-toggle" href="#">
									<i class="menu-icon fa fa-caret-right"></i>

									Layouts
									<b class="arrow fa fa-angle-down"></b>
								</a>

								<b class="arrow"></b>

								<ul class="submenu">
									<li class="">
										<a href="top-menu.html">
											<i class="menu-icon fa fa-caret-right"></i>
											Top Menu
										</a>

										<b class="arrow"></b>
									</li>

									<li class="">
										<a href="mobile-menu-1.html">
											<i class="menu-icon fa fa-caret-right"></i>
											Default Mobile Menu
										</a>

										<b class="arrow"></b>
									</li>

									<li class="">
										<a href="mobile-menu-2.html">
											<i class="menu-icon fa fa-caret-right"></i>
											Mobile Menu 2
										</a>

										<b class="arrow"></b>
									</li>

									<li class="">
										<a href="mobile-menu-3.html">
											<i class="menu-icon fa fa-caret-right"></i>
											Mobile Menu 3
										</a>

										<b class="arrow"></b>
									</li>
								</ul>
							</li>

							<li class="">
								<a href="typography.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Typography
								</a>

								<b class="arrow"></b>
							</li>

							<li class="active">
								<a href="elements.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Elements
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="buttons.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Buttons &amp; Icons
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="treeview.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Treeview
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="jquery-ui.html">
									<i class="menu-icon fa fa-caret-right"></i>
									jQuery UI
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="nestable-list.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Nestable Lists
								</a>

								<b class="arrow"></b>
							</li>

							<li class="hsub">
								<a class="dropdown-toggle" href="#">
									<i class="menu-icon fa fa-caret-right"></i>

									Three Level Menu
									<b class="arrow fa fa-angle-down"></b>
								</a>

								<b class="arrow"></b>

								<ul class="submenu">
									<li class="">
										<a href="#">
											<i class="menu-icon fa fa-leaf green"></i>
											Item #1
										</a>

										<b class="arrow"></b>
									</li>

									<li class="hsub">
										<a class="dropdown-toggle" href="#">
											<i class="menu-icon fa fa-pencil orange"></i>

											4th level
											<b class="arrow fa fa-angle-down"></b>
										</a>

										<b class="arrow"></b>

										<ul class="submenu">
											<li class="">
												<a href="#">
													<i class="menu-icon fa fa-plus purple"></i>
													Add Product
												</a>

												<b class="arrow"></b>
											</li>

											<li class="">
												<a href="#">
													<i class="menu-icon fa fa-eye pink"></i>
													View Products
												</a>

												<b class="arrow"></b>
											</li>
										</ul>
									</li>
								</ul>
							</li>
						</ul>
					</li>

					<li class="hsub">
						<a class="dropdown-toggle" href="#">
							<i class="menu-icon fa fa-list"></i>
							<span class="menu-text"> Tables </span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<li class="">
								<a href="tables.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Simple &amp; Dynamic
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="jqgrid.html">
									<i class="menu-icon fa fa-caret-right"></i>
									jqGrid plugin
								</a>

								<b class="arrow"></b>
							</li>
						</ul>
					</li>

					<li class="hsub">
						<a class="dropdown-toggle" href="#">
							<i class="menu-icon fa fa-pencil-square-o"></i>
							<span class="menu-text"> Forms </span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<li class="">
								<a href="form-elements.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Form Elements
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="form-wizard.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Wizard &amp; Validation
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="wysiwyg.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Wysiwyg &amp; Markdown
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="dropzone.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Dropzone File Upload
								</a>

								<b class="arrow"></b>
							</li>
						</ul>
					</li>

					<li class="">
						<a href="widgets.html">
							<i class="menu-icon fa fa-list-alt"></i>
							<span class="menu-text"> Widgets </span>
						</a>

						<b class="arrow"></b>
					</li>

					<li class="">
						<a href="calendar.html">
							<i class="menu-icon fa fa-calendar"></i>

							<span class="menu-text">
								Calendar

								<!-- #section:basics/sidebar.layout.badge -->
								<span title="" class="badge badge-transparent tooltip-error" data-original-title="2 Important Events">
									<i class="ace-icon fa fa-exclamation-triangle red bigger-130"></i>
								</span>

								<!-- /section:basics/sidebar.layout.badge -->
							</span>
						</a>

						<b class="arrow"></b>
					</li>

					<li class="">
						<a href="gallery.html">
							<i class="menu-icon fa fa-picture-o"></i>
							<span class="menu-text"> Gallery </span>
						</a>

						<b class="arrow"></b>
					</li>

					<li class="hsub">
						<a class="dropdown-toggle" href="#">
							<i class="menu-icon fa fa-tag"></i>
							<span class="menu-text"> More Pages </span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<li class="">
								<a href="profile.html">
									<i class="menu-icon fa fa-caret-right"></i>
									User Profile
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="inbox.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Inbox
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="pricing.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Pricing Tables
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="invoice.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Invoice
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="timeline.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Timeline
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="email.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Email Templates
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="login.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Login &amp; Register
								</a>

								<b class="arrow"></b>
							</li>
						</ul>
					</li>

					<li class="hsub">
						<a class="dropdown-toggle" href="#">
							<i class="menu-icon fa fa-file-o"></i>

							<span class="menu-text">
								Other Pages

								<!-- #section:basics/sidebar.layout.badge -->
								<span class="badge badge-primary">5</span>

								<!-- /section:basics/sidebar.layout.badge -->
							</span>

							<b class="arrow fa fa-angle-down"></b>
						</a>

						<b class="arrow"></b>

						<ul class="submenu">
							<li class="">
								<a href="faq.html">
									<i class="menu-icon fa fa-caret-right"></i>
									FAQ
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="error-404.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Error 404
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="error-500.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Error 500
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="grid.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Grid
								</a>

								<b class="arrow"></b>
							</li>

							<li class="">
								<a href="blank.html">
									<i class="menu-icon fa fa-caret-right"></i>
									Blank Page
								</a>

								<b class="arrow"></b>
							</li>
						</ul>
					</li>
				</ul><!-- /.nav-list -->

				<!-- #section:basics/sidebar.layout.minimize -->
				<div id="sidebar-collapse" class="sidebar-toggle sidebar-collapse">
					<i data-icon2="ace-icon fa fa-angle-double-right" data-icon1="ace-icon fa fa-angle-double-left" class="ace-icon fa fa-angle-double-left"></i>
				</div>

				<!-- /section:basics/sidebar.layout.minimize -->
				<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
				</script>
			</div>

			<!-- /section:basics/sidebar -->
			<div class="main-content">
				<!-- #section:basics/content.breadcrumbs -->
				<div id="breadcrumbs" class="breadcrumbs">
					<script type="text/javascript">
						try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
					</script>

					<ul class="breadcrumb">
						<li>
							<i class="ace-icon fa fa-home home-icon"></i>
							<a href="#">Home</a>
						</li>

						<li>
							<a href="#">UI &amp; Elements</a>
						</li>
						<li class="active">Elements</li>
					</ul><!-- /.breadcrumb -->

					<!-- #section:basics/content.searchbox -->
					<div id="nav-search" class="nav-search">
						<form class="form-search">
							<span class="input-icon">
								<input type="text" autocomplete="off" id="nav-search-input" class="nav-search-input" placeholder="Search ...">
								<i class="ace-icon fa fa-search nav-search-icon"></i>
							</span>
						</form>
					</div><!-- /.nav-search -->

					<!-- /section:basics/content.searchbox -->
				</div>

				<!-- /section:basics/content.breadcrumbs -->
				<div class="page-content">
					<!-- #section:settings.box -->
					<div id="ace-settings-container" class="ace-settings-container">
						<div id="ace-settings-btn" class="btn btn-app btn-xs btn-warning ace-settings-btn">
							<i class="ace-icon fa fa-cog bigger-150"></i>
						</div>

						<div id="ace-settings-box" class="ace-settings-box clearfix">
							<div class="pull-left width-50">
								<!-- #section:settings.skins -->
								<div class="ace-settings-item">
									<div class="pull-left">
										<select class="hide" id="skin-colorpicker">
											<option value="#438EB9" data-skin="no-skin">#438EB9</option>
											<option value="#222A2D" data-skin="skin-1">#222A2D</option>
											<option value="#C6487E" data-skin="skin-2">#C6487E</option>
											<option value="#D0D0D0" data-skin="skin-3">#D0D0D0</option>
										</select><div class="dropdown dropdown-colorpicker">		<a href="#" data-position="auto" class="dropdown-toggle" data-toggle="dropdown"><span style="background-color:#438EB9" class="btn-colorpicker"></span></a><ul class="dropdown-menu dropdown-caret"><li><a data-color="#438EB9" style="background-color:#438EB9;" href="#" class="colorpick-btn selected"></a></li><li><a data-color="#222A2D" style="background-color:#222A2D;" href="#" class="colorpick-btn"></a></li><li><a data-color="#C6487E" style="background-color:#C6487E;" href="#" class="colorpick-btn"></a></li><li><a data-color="#D0D0D0" style="background-color:#D0D0D0;" href="#" class="colorpick-btn"></a></li></ul></div>
									</div>
									<span>&nbsp; Choose Skin</span>
								</div>

								<!-- /section:settings.skins -->

								<!-- #section:settings.navbar -->
								<div class="ace-settings-item">
									<input type="checkbox" id="ace-settings-navbar" class="ace ace-checkbox-2">
									<label for="ace-settings-navbar" class="lbl"> Fixed Navbar</label>
								</div>

								<!-- /section:settings.navbar -->

								<!-- #section:settings.sidebar -->
								<div class="ace-settings-item">
									<input type="checkbox" id="ace-settings-sidebar" class="ace ace-checkbox-2">
									<label for="ace-settings-sidebar" class="lbl"> Fixed Sidebar</label>
								</div>

								<!-- /section:settings.sidebar -->

								<!-- #section:settings.breadcrumbs -->
								<div class="ace-settings-item">
									<input type="checkbox" id="ace-settings-breadcrumbs" class="ace ace-checkbox-2">
									<label for="ace-settings-breadcrumbs" class="lbl"> Fixed Breadcrumbs</label>
								</div>

								<!-- /section:settings.breadcrumbs -->

								<!-- #section:settings.rtl -->
								<div class="ace-settings-item">
									<input type="checkbox" id="ace-settings-rtl" class="ace ace-checkbox-2">
									<label for="ace-settings-rtl" class="lbl"> Right To Left (rtl)</label>
								</div>

								<!-- /section:settings.rtl -->

								<!-- #section:settings.container -->
								<div class="ace-settings-item">
									<input type="checkbox" id="ace-settings-add-container" class="ace ace-checkbox-2">
									<label for="ace-settings-add-container" class="lbl">
										Inside
										<b>.container</b>
									</label>
								</div>

								<!-- /section:settings.container -->
							</div><!-- /.pull-left -->

							<div class="pull-left width-50">
								<!-- #section:basics/sidebar.options -->
								<div class="ace-settings-item">
									<input type="checkbox" id="ace-settings-hover" class="ace ace-checkbox-2">
									<label for="ace-settings-hover" class="lbl"> Submenu on Hover</label>
								</div>

								<div class="ace-settings-item">
									<input type="checkbox" id="ace-settings-compact" class="ace ace-checkbox-2">
									<label for="ace-settings-compact" class="lbl"> Compact Sidebar</label>
								</div>

								<div class="ace-settings-item">
									<input type="checkbox" id="ace-settings-highlight" class="ace ace-checkbox-2">
									<label for="ace-settings-highlight" class="lbl"> Alt. Active Item</label>
								</div>

								<!-- /section:basics/sidebar.options -->
							</div><!-- /.pull-left -->
						</div><!-- /.ace-settings-box -->
					</div><!-- /.ace-settings-container -->

					<!-- /section:settings.box -->
					<div class="page-content-area">
						<div class="page-header">
							<h1>
								UI Elements
								<small>
									<i class="ace-icon fa fa-angle-double-right"></i>
									Common UI Features &amp; Elements
								</small>
							</h1>
						</div><!-- /.page-header -->

						<div class="row">
							<div class="col-xs-12">
								<!-- PAGE CONTENT BEGINS -->
								<div class="row">
									<div class="col-sm-6">
										<!-- #section:elements.tab -->
										<div class="tabbable">
											<ul id="myTab" class="nav nav-tabs">
												<li class="active">
													<a href="#home" data-toggle="tab">
														<i class="green ace-icon fa fa-home bigger-120"></i>
														Home
													</a>
												</li>

												<li>
													<a href="#messages" data-toggle="tab">
														Messages
														<span class="badge badge-danger">4</span>
													</a>
												</li>

												<li class="dropdown">
													<a href="#" class="dropdown-toggle" data-toggle="dropdown">
														Dropdown &nbsp;
														<i class="ace-icon fa fa-caret-down bigger-110 width-auto"></i>
													</a>

													<ul class="dropdown-menu dropdown-info">
														<li>
															<a href="#dropdown1" data-toggle="tab">@fat</a>
														</li>

														<li>
															<a href="#dropdown2" data-toggle="tab">@mdo</a>
														</li>
													</ul>
												</li>
											</ul>

											<div class="tab-content">
												<div class="tab-pane fade in active" id="home">
													<p>Raw denim you probably haven't heard of them jean shorts Austin.</p>
												</div>

												<div class="tab-pane fade" id="messages">
													<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.</p>
												</div>

												<div class="tab-pane fade" id="dropdown1">
													<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
												</div>

												<div class="tab-pane fade" id="dropdown2">
													<p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin.</p>
												</div>
											</div>
										</div>

										<!-- /section:elements.tab -->
									</div><!-- /.col -->

									<div class="vspace-6-sm"></div>

									<div class="col-sm-6">
										<div class="tabbable tabs-below">
											<div class="tab-content">
												<div class="tab-pane in active" id="home2">
													<p>Raw denim you probably haven't heard of them jean shorts Austin.</p>
												</div>

												<div class="tab-pane" id="profile2">
													<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.</p>
												</div>

												<div class="tab-pane" id="dropdown12">
													<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
												</div>
											</div>

											<ul id="myTab2" class="nav nav-tabs">
												<li class="active">
													<a href="#home2" data-toggle="tab">Home</a>
												</li>

												<li>
													<a href="#profile2" data-toggle="tab">Profile</a>
												</li>

												<li>
													<a href="#dropdown12" data-toggle="tab">More</a>
												</li>
											</ul>
										</div>
									</div>
								</div><!-- /.row -->

								<div class="space"></div>

								<div class="row">
									<div class="col-sm-6">
										<!-- #section:elements.tab.position -->
										<div class="tabbable tabs-left">
											<ul id="myTab3" class="nav nav-tabs">
												<li class="active">
													<a href="#home3" data-toggle="tab">
														<i class="pink ace-icon fa fa-tachometer bigger-110"></i>
														Home
													</a>
												</li>

												<li>
													<a href="#profile3" data-toggle="tab">
														<i class="blue ace-icon fa fa-user bigger-110"></i>
														Profile
													</a>
												</li>

												<li>
													<a href="#dropdown13" data-toggle="tab">
														<i class="ace-icon fa fa-rocket"></i>
														More
													</a>
												</li>
											</ul>

											<div class="tab-content">
												<div class="tab-pane in active" id="home3">
													<p>Raw denim you probably haven't heard of them jean shorts Austin.</p>
													<p>Raw denim you probably haven't heard of them jean shorts Austin.</p>
												</div>

												<div class="tab-pane" id="profile3">
													<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.</p>
													<p>Raw denim you probably haven't heard of them jean shorts Austin.</p>
												</div>

												<div class="tab-pane" id="dropdown13">
													<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
													<p>Raw denim you probably haven't heard of them jean shorts Austin.</p>
												</div>
											</div>
										</div>

										<!-- /section:elements.tab.position -->
									</div><!-- /.col -->

									<div class="vspace-6-sm"></div>

									<div class="col-sm-6">
										<!-- #section:elements.tab.option -->
										<div class="tabbable">
											<ul id="myTab4" class="nav nav-tabs padding-12 tab-color-blue background-blue">
												<li class="active">
													<a href="#home4" data-toggle="tab">Home</a>
												</li>

												<li>
													<a href="#profile4" data-toggle="tab">Profile</a>
												</li>

												<li>
													<a href="#dropdown14" data-toggle="tab">More</a>
												</li>
											</ul>

											<div class="tab-content">
												<div class="tab-pane in active" id="home4">
													<p>Raw denim you probably haven't heard of them jean shorts Austin.</p>
												</div>

												<div class="tab-pane" id="profile4">
													<p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.</p>
												</div>

												<div class="tab-pane" id="dropdown14">
													<p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade.</p>
												</div>
											</div>
										</div>

										<!-- /section:elements.tab.option -->
									</div><!-- /.col -->
								</div><!-- /.row -->

								<div class="hr hr-double hr-dotted hr18"></div>

								<div class="row">
									<div class="col-sm-6">
										<h3 class="row header smaller lighter blue">
											<span class="col-xs-6"> Accordion </span><!-- /.col -->

											<span class="col-xs-6">
												<span class="pull-right inline">
													<span class="grey smaller-80 bolder">style:</span>

													<span class="btn-toolbar inline middle no-margin">
														<span class="btn-group no-margin" data-toggle="buttons" id="accordion-style">
															<label class="btn btn-xs btn-yellow active">
																<input type="radio" value="1">
																1
															</label>

															<label class="btn btn-xs btn-yellow">
																<input type="radio" value="2">
																2
															</label>
														</span>
													</span>
												</span>
											</span><!-- /.col -->
										</h3>

										<!-- #section:elements.accordion -->
										<div class="accordion-style1 panel-group" id="accordion">
											<div class="panel panel-default">
												<div class="panel-heading">
													<h4 class="panel-title">
														<a href="#collapseOne" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle">
															<i data-icon-show="ace-icon fa fa-angle-right" data-icon-hide="ace-icon fa fa-angle-down" class="ace-icon fa fa-angle-down bigger-110"></i>
															&nbsp;Group Item #1
														</a>
													</h4>
												</div>

												<div id="collapseOne" class="panel-collapse collapse in">
													<div class="panel-body">
														Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
													</div>
												</div>
											</div>

											<div class="panel panel-default">
												<div class="panel-heading">
													<h4 class="panel-title">
														<a href="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
															<i data-icon-show="ace-icon fa fa-angle-right" data-icon-hide="ace-icon fa fa-angle-down" class="ace-icon fa fa-angle-right bigger-110"></i>
															&nbsp;Group Item #2
														</a>
													</h4>
												</div>

												<div id="collapseTwo" class="panel-collapse collapse">
													<div class="panel-body">
														Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
													</div>
												</div>
											</div>

											<div class="panel panel-default">
												<div class="panel-heading">
													<h4 class="panel-title">
														<a href="#collapseThree" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
															<i data-icon-show="ace-icon fa fa-angle-right" data-icon-hide="ace-icon fa fa-angle-down" class="ace-icon fa fa-angle-right bigger-110"></i>
															&nbsp;Group Item #3
														</a>
													</h4>
												</div>

												<div id="collapseThree" class="panel-collapse collapse">
													<div class="panel-body">
														Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.
													</div>
												</div>
											</div>
										</div>

										<!-- /section:elements.accordion -->
									</div><!-- /.col -->

									<div class="col-sm-6">
										<h3 class="header smaller lighter green">Progress Bar</h3>

										<div class="row">
											<div class="col-xs-8">
												<!-- #section:elements.progressbar -->
												<div data-percent="66%" class="progress pos-rel">
													<div style="width:66%;" class="progress-bar"></div>
												</div>

												<div data-percent="25%" class="progress progress-striped pos-rel">
													<div style="width: 25%;" class="progress-bar progress-bar-success"></div>
												</div>

												<!-- /section:elements.progressbar -->
												<div class="progress progress-small progress-striped active">
													<div style="width: 40%;" class="progress-bar progress-bar-warning"></div>
												</div>

												<div class="progress progress-mini">
													<div style="width: 35%;" class="progress-bar progress-danger"></div>
												</div>

												<div class="progress">
													<div style="width: 35%;" class="progress-bar progress-bar-success"></div>

													<div style="width: 20%;" class="progress-bar progress-bar-warning"></div>

													<div style="width: 10%;" class="progress-bar progress-bar-danger"></div>
												</div>

												<div class="progress progress-striped">
													<div style="width: 65%" class="progress-bar progress-bar-purple"></div>
												</div>

												<div class="progress progress-striped">
													<div style="width: 40%" class="progress-bar progress-bar-pink"></div>
												</div>

												<div class="progress progress-striped active">
													<div style="width: 60%" class="progress-bar progress-bar-yellow"></div>
												</div>

												<div class="progress progress-striped">
													<div style="width: 80%" class="progress-bar progress-bar-inverse"></div>
												</div>
											</div><!-- /.col -->

											<div class="col-xs-4 center">
												<!-- #section:plugins/charts.easypiechart -->
												<div data-color="#D15B47" data-percent="20" class="easy-pie-chart percentage" style="height: 75px; width: 75px; line-height: 74px; color: rgb(209, 91, 71);">
													<span class="percent">20</span>%
												<canvas height="81" width="81" style="height: 75px; width: 75px;"></canvas></div>

												<hr>
												<div data-color="#87CEEB" data-percent="55" class="easy-pie-chart percentage" style="height: 75px; width: 75px; line-height: 74px; color: rgb(135, 206, 235);">
													<span class="percent">55</span>%
												<canvas height="81" width="81" style="height: 75px; width: 75px;"></canvas></div>

												<hr>
												<div data-color="#87B87F" data-percent="90" class="easy-pie-chart percentage" style="height: 75px; width: 75px; line-height: 74px; color: rgb(135, 184, 127);">
													<span class="percent">90</span>%
												<canvas height="81" width="81" style="height: 75px; width: 75px;"></canvas></div>

												<!-- /section:plugins/charts.easypiechart -->
											</div><!-- /.col -->
										</div><!-- /.row -->
									</div><!-- /.col -->
								</div><!-- /.row -->

								<hr>
								<div class="row">
									<div class="col-sm-6">
										<div class="widget-box">
											<div class="widget-header">
												<h4 class="smaller">
													Tooltips
													<small>different directions and colors</small>
												</h4>
											</div>

											<div class="widget-body">
												<div class="widget-main">
													<p class="muted">
														Tight pants next level keffiyeh
														<a href="#" data-rel="tooltip" title="" data-original-title="Default tooltip">you probably</a>
														haven't heard of them. Farm-to-table seitan, mcsweeney's fixie sustainable quinoa 8-bit american apparel
														<a href="#" data-rel="tooltip" title="" data-original-title="Another tooltip">have a</a>
														terry richardson vinyl chambray. A really ironic artisan
														<a data-original-title="Another one here too" href="#" data-rel="tooltip">whatever</a>
														keytar, scenester farm-to-table banksy Austin
														<a href="#" data-rel="tooltip" title="" data-original-title="The last tip!">twitter</a>
														handle.
													</p>

													<hr>

													<!-- #section:elements.tooltip -->
													<p>
														<span title="" data-rel="tooltip" class="btn btn-sm" data-original-title="Default">Default</span>
														<span title="" data-placement="left" data-rel="tooltip" class="btn btn-warning btn-sm tooltip-warning" data-original-title="Left Warning">Left</span>
														<span title="" data-placement="right" data-rel="tooltip" class="btn btn-success btn-sm tooltip-success" data-original-title="Right Success">Right</span>
														<span title="" data-placement="top" data-rel="tooltip" class="btn btn-danger btn-sm tooltip-error" data-original-title="Top Danger">Top</span>
														<span title="" data-placement="bottom" data-rel="tooltip" class="btn btn-info btn-sm tooltip-info" data-original-title="Bottm Info">Bottom</span>
													</p>

													<!-- /section:elements.tooltip -->
												</div>
											</div>
										</div>
									</div><!-- /.col -->

									<div class="col-sm-6">
										<div class="widget-box">
											<div class="widget-header">
												<h4 class="smaller">Popovers</h4>
											</div>

											<div class="widget-body">
												<div class="widget-main">
													<!-- #section:elements.popover -->
													<p>
														<span data-content="Heads up! This alert needs your attention, but it's not super important." title="" data-rel="popover" class="btn btn-sm" data-original-title="Default">Default</span>
														<span data-content="Well done! You successfully read this important alert message." title="" data-placement="right" data-rel="popover" class="btn btn-success btn-sm popover-success" data-original-title="&lt;i class='ace-icon fa fa-check green'&gt;&lt;/i&gt; Right Success">Right</span>
														<span data-content="Warning! Best check yo self, you're not looking too good." title="" data-placement="left" data-rel="popover" class="btn btn-warning btn-sm popover-warning" data-original-title="&lt;i class='ace-icon fa fa-exclamation-triangle orange'&gt;&lt;/i&gt; Left Warning">Left</span>
													</p>

													<p>
														<span data-content="Oh snap! Change a few things up and try submitting again." data-original-title="&lt;i class='ace-icon fa fa-bolt red'&gt;&lt;/i&gt; Top Danger" data-placement="top" data-rel="popover" class="btn btn-danger btn-sm popover-error">Top</span>
														<span data-content="Heads up! This alert needs your attention, but it's not super important." title="" data-placement="bottom" data-rel="popover" class="btn btn-info btn-sm popover-info" data-original-title="Some Info">Bottom</span>
														<span data-content="Popover without a title!" data-placement="bottom" data-rel="popover" class="btn btn-inverse btn-sm popover-notitle" data-original-title="" title="">No Title</span>
													</p>

													<!-- /section:elements.popover -->
												</div>
											</div>
										</div>
									</div><!-- /.col -->
								</div><!-- /.row -->

								<hr>
								<div class="row">
									<div class="col-sm-6">
										<h3 class="header smaller lighter green">
											<i class="ace-icon fa fa-bullhorn"></i>
											Alerts
										</h3>

										<div class="alert alert-danger">
											<button data-dismiss="alert" class="close" type="button">
												<i class="ace-icon fa fa-times"></i>
											</button>

											<strong>
												<i class="ace-icon fa fa-times"></i>
												Oh snap!
											</strong>

											Change a few things up and try submitting again.
											<br>
										</div>

										<div class="alert alert-warning">
											<button data-dismiss="alert" class="close" type="button">
												<i class="ace-icon fa fa-times"></i>
											</button>
											<strong>Warning!</strong>

											Best check yo self, you're not looking too good.
											<br>
										</div>

										<div class="alert alert-block alert-success">
											<button data-dismiss="alert" class="close" type="button">
												<i class="ace-icon fa fa-times"></i>
											</button>

											<p>
												<strong>
													<i class="ace-icon fa fa-check"></i>
													Well done!
												</strong>
												You successfully read this important alert message.
											</p>

											<p>
												<button class="btn btn-sm btn-success">Do This</button>
												<button class="btn btn-sm">Or This One</button>
											</p>
										</div>

										<div class="alert alert-info">
											<button data-dismiss="alert" class="close" type="button">
												<i class="ace-icon fa fa-times"></i>
											</button>
											<strong>Heads up!</strong>

											This alert needs your attention, but it's not super important.
											<br>
										</div>
									</div><!-- /.col -->

									<div class="col-sm-6">
										<h3 class="row header smaller lighter orange">
											<span class="col-sm-8">
												<i class="ace-icon fa fa-bell"></i>
												Gritter Notifications
											</span><!-- /.col -->

											<span class="col-sm-4">
												<label class="pull-right inline">
													<small class="muted">Dark:</small>

													<input type="checkbox" class="ace ace-switch ace-switch-5" checked="" id="gritter-light">
													<span class="lbl middle"></span>
												</label>
											</span><!-- /.col -->
										</h3>

										<p>
											<i>Click to see</i>
										</p>

										<!-- #section:plugins/misc.gritter -->
										<p>
											<button id="gritter-regular" class="btn">Regular</button>
											<button id="gritter-sticky" class="btn btn-info">Sticky</button>
											<button id="gritter-without-image" class="btn btn-success">Without Image</button>
										</p>

										<p>
											<button id="gritter-error" class="btn btn-danger">Error</button>
											<button id="gritter-max3" class="btn btn-warning">Max 3</button>
											<button id="gritter-center" class="btn btn-primary">Center</button>
											<button id="gritter-remove" class="btn btn-inverse">Remove</button>
										</p>

										<!-- /section:plugins/misc.gritter -->
									</div><!-- /.col -->
								</div><!-- /.row -->

								<hr>
								<div class="row">
									<div class="col-sm-6">
										<div>
											<h3 class="header smaller lighter purple">
												Bootstrap Modals
												<small>(Bootbox.js)</small>
											</h3>

											<!-- #section:plugins/misc.bootbox -->
											<p>
												<button id="bootbox-regular" class="btn">Regular Dialog</button>
												<button id="bootbox-confirm" class="btn btn-info">Confirm</button>
												<button id="bootbox-options" class="btn btn-success">More Options</button>
											</p>

											<!-- /section:plugins/misc.bootbox -->
										</div><!-- /.row -->

										<div class="space-24"></div>

										<div class="row">
											<div class="col-xs-12">
												<h3 class="header smaller lighter grey">
													<i class="ace-icon fa fa-spinner fa-spin orange bigger-125"></i>
													Imageless Spinner
													<small>(spin.js)</small>
												</h3>
											</div>

											<div class="col-xs-12">
												<i>Change a value to begin</i>

												<div id="spinner-preview" class="pull-right center spinner-preview"></div>

												<form id="spinner-opts" class="form-horizontal">
													<!-- #section:plugins/jquery.slider -->
													<label class="inline">
														<small class="lighter" style="display: inline-block; width: 60px;">Lines:</small>

														<input type="text" value="12" data-step="2" data-max="16" data-min="5" name="lines" class="hidden" style="display: none;"><span class="ui-slider-small inline ui-slider- ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="width: 125px;"><div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 72.7273%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 72.7273%;"></span></span>
													</label>

													<div class="space-0"></div>

													<label class="inline">
														<small class="lighter" style="display: inline-block; width: 60px;">Length:</small>

														<input type="text" value="7" data-max="30" data-min="0" name="length" class="hidden" style="display: none;"><span class="ui-slider-small inline ui-slider-green ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="width: 125px;"><div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 23.3333%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 23.3333%;"></span></span>
													</label>

													<div class="space-0"></div>

													<label class="inline">
														<small class="lighter" style="display: inline-block; width: 60px;">Width:</small>

														<input type="text" value="4" data-max="20" data-min="2" name="width" class="hidden" style="display: none;"><span class="ui-slider-small inline ui-slider-red ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="width: 125px;"><div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 11.1111%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 11.1111%;"></span></span>
													</label>

													<div class="space-0"></div>

													<label class="inline">
														<small class="lighter" style="display: inline-block; width: 60px;">Radius:</small>

														<input type="text" value="10" data-max="40" data-min="0" name="radius" class="hidden" style="display: none;"><span class="ui-slider-small inline ui-slider-purple ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="width: 125px;"><div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 25%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 25%;"></span></span>
													</label>

													<div class="space-0"></div>

													<label class="inline">
														<small class="lighter" style="display: inline-block; width: 60px;">Corners:</small>

														<input type="text" value="1" data-step="0.1" data-max="1" data-min="0" name="corners" class="hidden" style="display: none;"><span class="ui-slider-small inline ui-slider-orange ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="width: 125px;"><div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 100%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 100%;"></span></span>
													</label>

													<div class="space-0"></div>

													<label class="inline">
														<small class="lighter" style="display: inline-block; width: 60px;">Rotate:</small>

														<input type="text" value="0" data-max="90" data-min="0" name="rotate" class="hidden" style="display: none;"><span class="ui-slider-small inline ui-slider-dark ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="width: 125px;"><div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 0%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 0%;"></span></span>
													</label>

													<div class="space-0"></div>

													<label class="inline">
														<small class="lighter" style="display: inline-block; width: 60px;">Trail:</small>

														<input type="text" value="60" data-max="100" data-min="10" name="trail" class="hidden" style="display: none;"><span class="ui-slider-small inline ui-slider- ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="width: 125px;"><div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 55.5556%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 55.5556%;"></span></span>
													</label>

													<div class="space-0"></div>

													<label class="inline">
														<small class="lighter" style="display: inline-block; width: 60px;">Speed:</small>

														<input type="text" value="1" data-step="0.1" data-max="2.2" data-min="0.5" name="speed" class="hidden" style="display: none;"><span class="ui-slider-small inline ui-slider-green ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all" style="width: 125px;"><div class="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" style="width: 50%;"></div><span tabindex="0" class="ui-slider-handle ui-state-default ui-corner-all" style="left: 50%;"></span></span>
													</label>

													<!-- /section:plugins/jquery.slider -->
												</form>
											</div><!-- /.row -->
										</div><!-- /.row -->
									</div><!-- /.col -->

									<div class="col-sm-6">
										<h3 class="header smaller lighter red">Bootstrap Wells</h3>

										<div class="well">
											<h4 class="green smaller lighter">Normal Well</h4>
											Use the well as a simple effect on an element to give it an inset effect.
										</div>

										<div class="well well-lg">
											<h4 class="blue">Large Well</h4>
											Control padding and rounded corners with two optional modifier classes.
										</div>
										<div class="well well-sm"> This is a small well </div>
									</div><!-- /.col -->
								</div><!-- /.row -->

								<div class="row">
									<div class="col-sm-6">
										<h3 class="header smaller lighter green">Dropdowns</h3>

										<!-- #section:elements.dropdown -->
										<div class="dropdown dropdown-preview">
											<ul class="dropdown-menu">
												<li>
													<a tabindex="-1" href="#">Action</a>
												</li>

												<li>
													<a tabindex="-1" href="#">Another action</a>
												</li>

												<li>
													<a tabindex="-1" href="#">Something else here</a>
												</li>

												<li class="divider"></li>

												<li>
													<a tabindex="-1" href="#">Separated link</a>
												</li>
											</ul>
										</div>

										<!-- /section:elements.dropdown -->

										<!-- #section:elements.dropdown.submenu -->
										<div class="dropdown dropdown-preview">
											<ul class="dropdown-menu dropdown-danger">
												<li>
													<a tabindex="-1" href="#">Action</a>
												</li>

												<li>
													<a tabindex="-1" href="#">Another action</a>
												</li>

												<li>
													<a tabindex="-1" href="#">Something else here</a>
												</li>

												<li class="divider"></li>

												<li class="dropdown-hover">
													<a class="clearfix" tabindex="-1" href="#">
														<span class="pull-left">More options</span>

														<i class="ace-icon fa fa-caret-right pull-right"></i>
													</a>

													<ul class="dropdown-menu dropdown-danger">
														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>
													</ul>
												</li>
											</ul>
										</div>

										<!-- /section:elements.dropdown.submenu -->
										<div class="dropup dropdown-preview">
											<ul class="dropdown-menu dropdown-light">
												<li>
													<a tabindex="-1" href="#">Action</a>
												</li>

												<li>
													<a tabindex="-1" href="#">Another action</a>
												</li>

												<li>
													<a tabindex="-1" href="#">Something else here</a>
												</li>

												<li class="divider"></li>

												<li class="dropup dropdown-hover">
													<a class="clearfix" tabindex="-1" href="#">
														<span class="pull-left">More options</span>

														<i class="ace-icon fa fa-caret-right pull-right"></i>
													</a>

													<ul class="dropdown-menu pull-left">
														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>
													</ul>
												</li>
											</ul>
										</div>

										<div class="dropup dropdown-preview">
											<ul class="dropdown-menu dropdown-purple">
												<li>
													<a tabindex="-1" href="#">Action</a>
												</li>

												<li>
													<a tabindex="-1" href="#">Another action</a>
												</li>

												<li>
													<a tabindex="-1" href="#">Something else here</a>
												</li>

												<li class="divider"></li>

												<li class="dropdown-hover dropup">
													<a class="clearfix" tabindex="-1" href="#">
														<span class="pull-left">More options</span>

														<i class="ace-icon fa fa-caret-left pull-right"></i>
													</a>

													<ul class="dropdown-menu dropdown-menu-right">
														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>

														<li>
															<a tabindex="-1" href="#">Second level link</a>
														</li>
													</ul>
												</li>
											</ul>
										</div>

										<!-- #section:elements.dropdown.small -->
										<div class="dropdown dropdown-preview">
											<ul class="dropdown-menu dropdown-icon-only dropdown-50 dropdown-light">
												<li class="action-buttons">
													<a class="center" tabindex="-1" href="#">
														<i class="fa fa-flag blue bigger-130"></i>
													</a>
												</li>

												<li class="action-buttons">
													<a class="center" tabindex="-1" href="#">
														<i class="fa fa-flag red bigger-130"></i>
													</a>
												</li>

												<li class="action-buttons">
													<a class="center" tabindex="-1" href="#">
														<i class="fa fa-flag green bigger-130"></i>
													</a>
												</li>

												<li class="action-buttons">
													<a class="center" tabindex="-1" href="#">
														<i class="fa fa-flag orange bigger-130"></i>
													</a>
												</li>
											</ul>
										</div>

										<!-- /section:elements.dropdown.small -->
									</div>

									<div class="col-sm-6">
										<h3 class="row header smaller lighter blue">
											<span class="col-sm-7">
												<i class="ace-icon fa fa-th-large"></i>
												Pills
											</span><!-- /.col -->

											<span class="col-sm-5">
												<label class="pull-right inline">
													<small class="muted">Stacked:</small>

													<input type="checkbox" class="ace ace-switch ace-switch-5" id="id-pills-stacked">
													<span class="lbl middle"></span>
												</label>
											</span><!-- /.col -->
										</h3>

										<ul class="nav nav-pills">
											<li class="active">
												<a href="#">Home</a>
											</li>

											<li class="disabled">
												<a href="#">Profile</a>
											</li>

											<li>
												<a href="#">Messages</a>
											</li>
										</ul>
									</div>
								</div>

								<script type="text/javascript">
									var $path_assets = "../assets";//this will be used in gritter alerts containing images
								</script>

								<!-- PAGE CONTENT ENDS -->
							</div><!-- /.col -->
						</div><!-- /.row -->
					</div><!-- /.page-content-area -->
				</div><!-- /.page-content -->
			</div><!-- /.main-content -->

			<div class="footer">
				<div class="footer-inner">
					<!-- #section:basics/footer -->
					<div class="footer-content">
						<span class="bigger-120">
							<span class="blue bolder">Ace</span>
							Application &copy; 2013-2014
						</span>

						&nbsp; &nbsp;
						<span class="action-buttons">
							<a href="#">
								<i class="ace-icon fa fa-twitter-square light-blue bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-facebook-square text-primary bigger-150"></i>
							</a>

							<a href="#">
								<i class="ace-icon fa fa-rss-square orange bigger-150"></i>
							</a>
						</span>
					</div>

					<!-- /section:basics/footer -->
				</div>
			</div>

			<a class="btn-scroll-up btn btn-sm btn-inverse" id="btn-scroll-up" href="#">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
		</div>